services:
  postgres_db:
    image: pgvector/pgvector:0.6.2-pg16
    container_name: postgres_db
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: nouha
      POSTGRES_PASSWORD: nouha
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: "exit 0"
  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmine
    restart: always
    ports:
      - "44:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nouha@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nouha
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db
volumes:
  postgres_db_data:
  pgadmin_data:

